!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.14 (r7114) - 22 Oct 2018 09:36
!
!  Differentiation of iea_bp_model_fortran in forward (tangent) mode:
!   variations   of useful results: wtvelocity
!   with respect to varying inputs: rotordiameter turbinexw turbineyw
!   RW status of diff variables: rotordiameter:in turbinexw:in
!                wtvelocity:out turbineyw:in
! Created by Jared J. Thomas, 2018
! FLight Optimization and Wind Laboratory (FLOW Lab)
! Brigham Young University
! implementation of the Bastankhah and Porte Agel (BPA) wake model for IEA case studies case 1
SUBROUTINE IEA_BP_MODEL_FORTRAN_DV(nturbines, turbinexw, turbinexwd, &
& turbineyw, turbineywd, rotordiameter, rotordiameterd, wind_speed, wec&
& , wtvelocity, wtvelocityd, nbdirs)
!  USE DIFFSIZES
!  Hint: nbdirs should be the maximum number of differentiation directions
  IMPLICIT NONE
  INTRINSIC KIND
! define precision to be the standard for a double precision ! on local system
  INTEGER, PARAMETER :: dp=KIND(0.d0)
! in
  INTEGER, INTENT(IN) :: nturbines
  REAL(dp), DIMENSION(nturbines), INTENT(IN) :: turbinexw, turbineyw
  REAL(dp), DIMENSION(nbdirs, nturbines), INTENT(IN) :: turbinexwd, &
& turbineywd
  REAL(dp), DIMENSION(nturbines), INTENT(IN) :: rotordiameter
  REAL(dp), DIMENSION(nbdirs, nturbines), INTENT(IN) :: &
& rotordiameterd
  REAL(dp), INTENT(IN) :: wind_speed, wec
! local (General)
  REAL(dp), DIMENSION(nturbines) :: loss, loss_array
  REAL(dp), DIMENSION(nbdirs, nturbines) :: lossd, loss_arrayd
  REAL(dp) :: ct, k, x, y, sigma, exponent, radical
  REAL(dp), DIMENSION(nbdirs) :: xd, yd, sigmad, exponentd, radicald
  INTEGER :: turb, turbi
! model out
  REAL(dp), DIMENSION(nturbines), INTENT(OUT) :: wtvelocity
  REAL(dp), DIMENSION(nbdirs, nturbines), INTENT(OUT) :: wtvelocityd
  INTRINSIC SQRT, EXP, SUM
  REAL(dp) :: result1
  REAL(dp), DIMENSION(nbdirs) :: result1d
  INTEGER :: nd
  INTEGER :: nbdirs
!"""Return each turbine's total loss due to wake from upstream turbines"""
! Equations and values explained in <iea37-wakemodel.pdf>
! Constant thrust coefficient
  ct = 4.0_dp*1.0_dp/3.0_dp*(1.0_dp-1.0_dp/3.0_dp)
! Constant, relating to a turbulence intensity of 0.075
  k = 0.0324555_dp
! Array holding the wake deficit seen at each turbine
  loss = 0.0_dp
  wtvelocity = 0.0_dp
  wtvelocityd(:, :) = 0.0_8
  lossd(:, :) = 0.0_8
! Looking at each turb (Primary)
  DO turbi=1,nturbines
    loss_array = 0.0_dp
    loss_arrayd(:, :) = 0.0_8
! Looking at all other turbs (Target)
    DO turb=1,nturbines
      DO nd=1,nbdirs
! Calculate the x-dist
        xd(nd) = turbinexwd(nd, turbi) - turbinexwd(nd, turb)
! And the y-offset
        yd(nd) = turbineywd(nd, turbi) - turbineywd(nd, turb)
      END DO
      x = turbinexw(turbi) - turbinexw(turb)
      y = turbineyw(turbi) - turbineyw(turb)
      IF (x .GT. 0.0_dp) THEN
! If Primary is downwind of the Target
! Calculate the wake loss
        result1 = SQRT(8.0_dp)
        sigma = k*x + rotordiameter(turb)/result1
! Calculate the wake loss
        result1 = SQRT(8.0_dp)
        sigma = k*x + rotordiameter(turb)/result1
        radical = 1.0_dp - ct/(8.0_dp*sigma**2/rotordiameter(turb)**2)
        DO nd=1,nbdirs
          sigmad(nd) = k*xd(nd) + rotordiameterd(nd, turb)/result1
! Simplified Bastankhah Gaussian wake model
          exponentd(nd) = -(0.5_dp*2*y*(yd(nd)*wec*sigma-y*wec*sigmad(nd&
&           ))/(wec**3*sigma**3))
          radicald(nd) = ct*(8.0_dp*2*sigma*sigmad(nd)*rotordiameter(&
&           turb)**2-8.0_dp*sigma**2*2*rotordiameter(turb)*&
&           rotordiameterd(nd, turb))/rotordiameter(turb)**4/(8.0_dp*&
&           sigma**2/rotordiameter(turb)**2)**2
          IF (radical .EQ. 0.0) THEN
            result1d(nd) = 0.0_8
          ELSE
            result1d(nd) = radicald(nd)/(2.0*SQRT(radical))
          END IF
        END DO
        exponent = -(0.5_dp*(y/(wec*sigma))**2)
        result1 = SQRT(radical)
        DO nd=1,nbdirs
          loss_arrayd(nd, turb) = (1.0_dp-result1)*exponentd(nd)*EXP(&
&           exponent) - result1d(nd)*EXP(exponent)
        END DO
        loss_array(turb) = (1.0_dp-result1)*EXP(exponent)
      END IF
      DO nd=1,nbdirs
! Note that if the Target is upstream, loss is defaulted to zero
        lossd(nd, turbi) = lossd(nd, turbi) + 2*loss_array(turb)*&
&         loss_arrayd(nd, turb)
      END DO
      loss(turbi) = loss(turbi) + loss_array(turb)**2
    END DO
    DO nd=1,nbdirs
! Total wake losses from all upstream turbs, using sqrt of sum of sqrs
      IF (loss(turbi) .EQ. 0.0) THEN
        lossd(nd, turbi) = 0.0_8
      ELSE
        lossd(nd, turbi) = lossd(nd, turbi)/(2.0*SQRT(loss(turbi)))
      END IF
! Effective windspeed is freestream multiplied by wake deficits
      wtvelocityd(nd, turbi) = -(wind_speed*lossd(nd, turbi))
    END DO
    loss(turbi) = SQRT(loss(turbi))
    wtvelocity(turbi) = wind_speed*(1.-loss(turbi))
  END DO
END SUBROUTINE IEA_BP_MODEL_FORTRAN_DV

